# A basic action that deploys to the server 

name: CI

on: [push]

jobs:
  test:
    runs-on: Ubuntu-22.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

  deploy:
    needs: test
    if: ${{ github.ref_name == 'main' }}
    runs-on: ubuntu-latest
    steps:
    - name: deploy on production server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script_stop: true
        script: |
          cd birthdaiii
          systemctl --user stop birthdaiii.service
          git pull
          npm install
          npm run build
          systemctl --user start birthdaiii.service